name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
     
      - run: npm install -g firebase-tools
    

      - run: firebase deploy --token ${{ secrets.FIREBASE_TOKEN }}

