name: Firebase Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      # If your project needs a build step, uncomment these lines:
      # - name: Install dependencies
      #   run: npm install
      #
      # - name: Build project
      #   run: npm run build

      - name: Deploy to Firebase Hosting
        run: firebase deploy --only hosting --project matcha-beyond --token ${{ secrets.FIREBASE_TOKEN }}


